<?php

/**
 * @file
 * Contains transistore.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function transistore_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the transistore module.
    case 'help.page.transistore':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module regroupant les fonctions de gestion et d&#039;administration de l&#039;association') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function transistore_theme() {
  return [
    'transistore' => [
      'render element' => 'children',
    ],
  ];
}
